In [2]:
import numpy as np
import pandas as pd


In [ ]:
arr = np.array([1,2,3,4,5])
np.ndim(arr)

1

DEFINE EL TIPO DEL ARRAY

In [ ]:
arr = arr.astype(np.int8)
arr

array([1, 2, 3, 4, 5], dtype=int8)

In [ ]:
array2 = np.array([2,3,5,6,7], dtype=np.float64)

DEFINE LA DIMENSION AL CREAR EL ARRAY

In [ ]:
arr2 = np.array([8,9,5],ndmin=12)
arr2


array([[[[[[[[[[[[8, 9, 5]]]]]]]]]]]])

AJUSTA EL ARRAY A LA DIMENSION RECOMENDADA (MINIMA)

In [ ]:
arr2 = np.squeeze(arr2)
arr2

array([8, 9, 5])

CREA UNA MATRIZ CON DIAGONAL UNOS - np.

In [ ]:
matriz = np.eye(4,dtype=np.int8)
matriz

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int8)

CREACION DE MATRICES PREDEFINIDAS

In [ ]:
arr = np.ones((4,4)) #matriz creada con unos podemos usar tambien zeros
arr2 = np.arange(3,9) #crear array con rango del 3 al 9(no incluye 9)
arr2

array([3, 4, 5, 6, 7, 8])

CREARA ARREGLO DEL 1 AL 10 CON 11 ELEMENTOS

In [ ]:
lin = np.linspace(1,10,11)
lin

array([ 1. ,  1.9,  2.8,  3.7,  4.6,  5.5,  6.4,  7.3,  8.2,  9.1, 10. ])

SABER LA ESTRUCTURA DE LA MATRIZ

In [ ]:
arr4 = np.random.randint(0,100,(4,4))
arr4.shape

(4, 4)

MODIFICAR LA ESTRUCTURA DE LA MATRIZ

In [ ]:
arr5 = np.random.randint(0,100,(4,8))
arr5
arr6 = np.reshape(arr5,(2,16))

96

CREAR UNA MATRIZ DE NUMERO ALEATORIOS ENTRE 0,20 DE ESTRUCUTRA 3 Y 5

In [ ]:
arr = np.random.randint(0,20,(3,5))
arr

array([[16,  8, 12,  2, 19],
       [14,  1, 10, 13,  2],
       [13, 18, 12,  2, 12]])

In [ ]:
lista1 = np.array([[1,3,5],[7,9,8]])
lista2 = np.array([4,2,1])


FUNCIONES PRINCIPALES 

In [ ]:
arr5.ptp() #SABER LA DISTANCIA ENTRE EL ULTIMO ELEMENTO Y EL FINAL
arr5.max() #si pones un numero pides que busque el valor por fila
arr5.min()
arr5.argmax() #busqueda de indice mayot
arr5.argmin()
arr5.sort()
np.percentile(arr5,50)
np.media(arr5)
np.std(arr5)
np.var(arr5)
np.mean(arr5)

EXPANDIR DIMENSION POR LA FILA.

In [ ]:
lista2 = np.expand_dims(lista2,axis=0)
lista2

array([[4, 2, 1]])

UNIR ARRAY EN UNA MATRIZ...RECUERDA QUE LISTA2.T SIGNIFICA QUE HARAS LA TRANSPUESTA

In [ ]:
matriz = np.concatenate((lista1,lista2),axis=0)

In [ ]:
matriz
matriz.shape
matriz2 = np.reshape(matriz,(9,1))
matriz2

array([[1],
       [3],
       [5],
       [7],
       [9],
       [8],
       [4],
       [2],
       [1]])

COMO COPIAR..IMPORTANTE

In [ ]:
mat2 = np.random.randint(0,200,(5,6))
mat2
mat3 = mat2.copy()
mat2

array([[115,  51, 185, 118,  86,   6],
       [ 57, 177,  21,  52, 188, 148],
       [ 27,   7, 168, 131,  41,  44],
       [171, 129, 143, 156, 113,  59],
       [ 40, 134,  10, 197, 113, 123]])

In [ ]:
mat3 = np.reshape(mat3,(6,5))
mat3

array([[115,  51, 185, 118,  86],
       [  6,  57, 177,  21,  52],
       [188, 148,  27,   7, 168],
       [131,  41,  44, 171, 129],
       [143, 156, 113,  59,  40],
       [134,  10, 197, 113, 123]])

In [ ]:
mat2

array([[115,  51, 185, 118,  86,   6],
       [ 57, 177,  21,  52, 188, 148],
       [ 27,   7, 168, 131,  41,  44],
       [171, 129, 143, 156, 113,  59],
       [ 40, 134,  10, 197, 113, 123]])

CONDICIONES y OPERACIONES

In [ ]:
mat6 = np.random.randint(0,14,(1,10))
mat6[mat6>8]


array([13,  9, 10, 13])

In [ ]:
mat6*2

array([[ 0,  6, 10, 26, 18, 16,  6, 20,  0, 26]])

PRODUCTO PUNTO ENTRE MATRICES

In [ ]:
mat1 = np.matmul(mat2,mat3) #o tambiem mat2@mat3.T

# **PANDAS**

SERIE DE PANDA

In [ ]:
psserie = pd.Series(['Nava','Messi'], index=[1,2])
psserie

1     Nava
2    Messi
dtype: object

In [ ]:
psdic = {1:'Navas', 30:'Messi'} #los diccionarios tambien pueden ser creados en pandas
psdic = pd.Series(psdic)
psdic

1     Navas
30    Messi
dtype: object

In [ ]:
psdic2 = {'Jugador':['Navas','Messi'],
          'Peso':[70,65],
          'Goles':[20,140],          
          }


In [ ]:
psdt = pd.DataFrame(psdic2, index=[1,30])
psdt.columns #convierte los encabezados de las columnas en un array


Index(['Jugador', 'Peso', 'Goles'], dtype='object')

In [1]:
import pandas as pd
df_movies = pd.read_csv('C:\\Users\\user\\Documents\\Coding\\python\\numpy_pandas\\n_movies.csv',sep=',') #header=2 ..decimos que el header esta en la fila 2
df_movies.head(4)

title         year certificate duration  \
0         Cobra Kai     (2018– )       TV-14   30 min   
1         The Crown     (2016– )       TV-MA   58 min   
2  Better Call Saul  (2015–2022)       TV-MA   46 min   
3     Devil in Ohio       (2022)       TV-MA  356 min   

                       genre  rating  \
0      Action, Comedy, Drama     8.5   
1  Biography, Drama, History     8.7   
2               Crime, Drama     8.9   
3     Drama, Horror, Mystery     5.9   

                                         description  \
0  Decades after their 1984 All Valley Karate Tou...   
1  Follows the political rivalries and romance of...   
2  The trials and tribulations of criminal lawyer...   
3  When a psychiatrist shelters a mysterious cult...   

                                               stars    votes  
0  ['Ralph Macchio, ', 'William Zabka, ', 'Courtn...  177,031  
1  ['Claire Foy, ', 'Olivia Colman, ', 'Imelda St...  199,885  
2  ['Bob Odenkirk, ', 'Rhea Seehorn, ', 'Jonathan...  501,384  
3  ['Emily Deschanel, ', 'Sam Jaeger, ', 'Gerardo...    9,773

LOC = por labels

In [4]:
df_movies.loc[2:7,['title','year']]

title         year
2        Better Call Saul  (2015–2022)
3           Devil in Ohio       (2022)
4  Cyberpunk: Edgerunners     (2022– )
5             The Sandman     (2022– )
6          Rick and Morty     (2013– )
7            Breaking Bad  (2008–2013)

In [11]:
df_movies.loc[9951:df_movies.shape[0],['title','votes']]

title      votes
9951      Breaking Bad  1,831,359
9952    The Imperfects      3,130
9953  The Walking Dead    970,067
9954         The Crown    199,898
9955      Supernatural    439,601
9956     Devil in Ohio      9,786

ILOC = INDICES

In [ ]:
df_movies.iloc[1,5]*2 #aca le dices que te de la informacion de la fila 1 columna 5 y lo multiplique * 2 ( valor en 5=8.7)

17.4

In [ ]:
df_movies.iloc[:2,:]

title      year certificate duration                      genre  \
0  Cobra Kai  (2018– )       TV-14   30 min      Action, Comedy, Drama   
1  The Crown  (2016– )       TV-MA   58 min  Biography, Drama, History   

   rating                                        description  \
0     8.5  Decades after their 1984 All Valley Karate Tou...   
1     8.7  Follows the political rivalries and romance of...   

                                               stars    votes  
0  ['Ralph Macchio, ', 'William Zabka, ', 'Courtn...  177,031  
1  ['Claire Foy, ', 'Olivia Colman, ', 'Imelda St...  199,885

In [1]:
df_movies.sort_values("rating").dropna()

NameError: name 'df_movies' is not defined

DROP COLUMNS AND ROWS

In [ ]:
df_movies.drop(9952,axis=0,inplace=True) # aqui borramos el indice 9952 de la FILA (para columna axis=1), ojo que no lo sustituye, si solo se quiere mostrar sin determinado valor no usar INPLACE

In [25]:
anio = lambda x: x[1:5]
anio(df_movies['year'])
print(anio)
df_movies[df_movies['rating']>8.1]

<function <lambda> at 0x000002429EA4FEB0>


title         year certificate duration  \
0                  Cobra Kai     (2018– )       TV-14   30 min   
1                  The Crown     (2016– )       TV-MA   58 min   
2           Better Call Saul  (2015–2022)       TV-MA   46 min   
4     Cyberpunk: Edgerunners     (2022– )       TV-MA   24 min   
6             Rick and Morty     (2013– )       TV-MA   23 min   
...                      ...          ...         ...      ...   
9947            Black Mirror  (2011–2019)       TV-MA   60 min   
9948         Stranger Things     (2016– )       TV-14   51 min   
9951            Breaking Bad  (2008–2013)       TV-MA   49 min   
9954               The Crown     (2016– )       TV-MA   58 min   
9955            Supernatural  (2005–2020)       TV-14   44 min   

                             genre  rating  \
0            Action, Comedy, Drama     8.5   
1        Biography, Drama, History     8.7   
2                     Crime, Drama     8.9   
4     Animation, Action, Adventure     8.6   
6     Animation, Adventure, Comedy     9.2   
...                            ...     ...   
9947        Drama, Mystery, Sci-Fi     8.8   
9948        Drama, Fantasy, Horror     8.7   
9951        Crime, Drama, Thriller     9.5   
9954     Biography, Drama, History     8.7   
9955        Drama, Fantasy, Horror     8.4   

                                            description  \
0     Decades after their 1984 All Valley Karate Tou...   
1     Follows the political rivalries and romance of...   
2     The trials and tribulations of criminal lawyer...   
4     A Street Kid trying to survive in a technology...   
6     An animated series that follows the exploits o...   
...                                                 ...   
9947  An anthology series exploring a twisted, high-...   
9948  When a young boy disappears, his mother, a pol...   
9951  A high school chemistry teacher diagnosed with...   
9954  Follows the political rivalries and romance of...   
9955  Two brothers follow their father's footsteps a...   

                                                  stars      votes  
0     ['Ralph Macchio, ', 'William Zabka, ', 'Courtn...    177,031  
1     ['Claire Foy, ', 'Olivia Colman, ', 'Imelda St...    199,885  
2     ['Bob Odenkirk, ', 'Rhea Seehorn, ', 'Jonathan...    501,384  
4     ['Zach Aguilar, ', 'Kenichiro Ohashi, ', 'Emi ...     15,413  
6     ['Justin Roiland, ', 'Chris Parnell, ', 'Spenc...    502,160  
...                                                 ...        ...  
9947  ['Daniel Lapaine, ', 'Hannah John-Kamen, ', 'M...    535,785  
9948  ['Millie Bobby Brown, ', 'Finn Wolfhard, ', 'W...  1,149,902  
9951  ['Bryan Cranston, ', 'Aaron Paul, ', 'Anna Gun...  1,831,359  
9954  ['Claire Foy, ', 'Olivia Colman, ', 'Imelda St...    199,898  
9955  ['Jared Padalecki, ', 'Jensen Ackles, ', 'Jim ...    439,601  

[970 rows x 9 columns]

BORRAR DUPLICADAS

In [ ]:
df_movies.drop_duplicates('duration') #recuerda que si pones inplace=True puedes borrar permanentemente del dataframe

title         year  \
0                                             Cobra Kai     (2018– )   
1                                             The Crown     (2016– )   
2                                      Better Call Saul  (2015–2022)   
3                                         Devil in Ohio       (2022)   
4                                Cyberpunk: Edgerunners     (2022– )   
...                                                 ...          ...   
5443                Lalbaug Parel: Zali Mumbai Sonyachi       (2010)   
5596                  My Love: Six Stories of True Love       (2021)   
5946  Nisman. The Prosecutor, the President and the Spy  (2019–2020)   
5985        Reasonable Doubt: A Tale of Two Kidnappings       (2021)   
7470                            Nietzsche and the Nazis       (2006)   

     certificate duration                         genre  rating  \
0          TV-14   30 min         Action, Comedy, Drama     8.5   
1          TV-MA   58 min     Biography, Drama, History     8.7   
2          TV-MA   46 min                  Crime, Drama     8.9   
3          TV-MA  356 min        Drama, Horror, Mystery     5.9   
4          TV-MA   24 min  Animation, Action, Adventure     8.6   
...          ...      ...                           ...     ...   
5443   Not Rated  146 min                        Action     7.2   
5596       TV-PG  418 min          Documentary, Romance     7.4   
5946         NaN  373 min   Documentary, Crime, History     7.6   
5985       TV-MA  186 min            Documentary, Crime     7.6   
7470          PG  165 min                   Documentary     7.7   

                                            description  \
0     Decades after their 1984 All Valley Karate Tou...   
1     Follows the political rivalries and romance of...   
2     The trials and tribulations of criminal lawyer...   
3     When a psychiatrist shelters a mysterious cult...   
4     A Street Kid trying to survive in a technology...   
...                                                 ...   
5443  Mill workers are subjected to atrocities and t...   
5596  Six longtime couples in different parts of the...   
5946  The suspicious death of Alberto Nisman, invest...   
5985  A fender bender that turned into a kidnapping ...   
7470  Directors were Christopher Vaughan and John Ba...   

                                                  stars    votes  
0     ['Ralph Macchio, ', 'William Zabka, ', 'Courtn...  177,031  
1     ['Claire Foy, ', 'Olivia Colman, ', 'Imelda St...  199,885  
2     ['Bob Odenkirk, ', 'Rhea Seehorn, ', 'Jonathan...  501,384  
3     ['Emily Deschanel, ', 'Sam Jaeger, ', 'Gerardo...    9,773  
4     ['Zach Aguilar, ', 'Kenichiro Ohashi, ', 'Emi ...   15,413  
...                                                 ...      ...  
5443  ['Mahesh Manjrekar', '| ', '    Stars:', 'Vina...      335  
5596  ['Ren Hanami, ', 'Susana Ballesteros, ', 'Asit...      296  
5946  ['Dexter Filkins, ', 'Hernán Cappiello, ', 'Os...      597  
5985                                                 []      204  
7470  ['Frank Michaels', '| ', '    Star:', 'Stephen...       57  

[292 rows x 9 columns]

In [ ]:
df_movies['Nueva'] = np.arange(0,df_movies.shape[0]) #agregar columna nueva
df_movies

title         year certificate duration  \
0                  Cobra Kai     (2018– )       TV-14   30 min   
1                  The Crown     (2016– )       TV-MA   58 min   
2           Better Call Saul  (2015–2022)       TV-MA   46 min   
3              Devil in Ohio       (2022)       TV-MA  356 min   
4     Cyberpunk: Edgerunners     (2022– )       TV-MA   24 min   
...                      ...          ...         ...      ...   
9952          The Imperfects     (2022– )       TV-MA   45 min   
9953        The Walking Dead  (2010–2022)       TV-MA   44 min   
9954               The Crown     (2016– )       TV-MA   58 min   
9955            Supernatural  (2005–2020)       TV-14   44 min   
9956           Devil in Ohio       (2022)       TV-MA  356 min   

                             genre  rating  \
0            Action, Comedy, Drama     8.5   
1        Biography, Drama, History     8.7   
2                     Crime, Drama     8.9   
3           Drama, Horror, Mystery     5.9   
4     Animation, Action, Adventure     8.6   
...                            ...     ...   
9952      Action, Adventure, Drama     6.3   
9953       Drama, Horror, Thriller     8.1   
9954     Biography, Drama, History     8.7   
9955        Drama, Fantasy, Horror     8.4   
9956        Drama, Horror, Mystery     5.9   

                                            description  \
0     Decades after their 1984 All Valley Karate Tou...   
1     Follows the political rivalries and romance of...   
2     The trials and tribulations of criminal lawyer...   
3     When a psychiatrist shelters a mysterious cult...   
4     A Street Kid trying to survive in a technology...   
...                                                 ...   
9952  After an experimental gene therapy turns them ...   
9953  Sheriff Deputy Rick Grimes wakes up from a com...   
9954  Follows the political rivalries and romance of...   
9955  Two brothers follow their father's footsteps a...   
9956  When a psychiatrist shelters a mysterious cult...   

                                                  stars    votes  Nueva  
0     ['Ralph Macchio, ', 'William Zabka, ', 'Courtn...  177,031      0  
1     ['Claire Foy, ', 'Olivia Colman, ', 'Imelda St...  199,885      1  
2     ['Bob Odenkirk, ', 'Rhea Seehorn, ', 'Jonathan...  501,384      2  
3     ['Emily Deschanel, ', 'Sam Jaeger, ', 'Gerardo...    9,773      3  
4     ['Zach Aguilar, ', 'Kenichiro Ohashi, ', 'Emi ...   15,413      4  
...                                                 ...      ...    ...  
9952  ['Morgan Taylor Campbell, ', 'Italia Ricci, ',...    3,130   9952  
9953  ['Andrew Lincoln, ', 'Norman Reedus, ', 'Melis...  970,067   9953  
9954  ['Claire Foy, ', 'Olivia Colman, ', 'Imelda St...  199,898   9954  
9955  ['Jared Padalecki, ', 'Jensen Ackles, ', 'Jim ...  439,601   9955  
9956  ['Emily Deschanel, ', 'Sam Jaeger, ', 'Gerardo...    9,786   9956  

[9957 rows x 10 columns]

In [14]:
import numpy as np
matr = np.random.randint(1,200,(2,5))
print(matr)

[[129  80  40 156 167]
 [ 76 180  79 159  29]]


Agregar FILAS

In [ ]:
#df_mov2 = pd.DataFrame(df_movies)
df_add = pd.DataFrame({'title':['Soltera codiciada'],'year':['(2019)'],'certificate':['TV-MA'],'duration':['100 min'],'genre':['Comedy'],'rating':['4.6'],'description':['The bachelor left his bride 2 weeks before the  wedding'],'stars':['[Ciccia, Chuima,]'],'votes':['150,484']})
df_new = pd.concat([df_movies,df_add])

In [4]:
df_new.tail(3)

NameError: name 'df_new' is not defined

In [3]:
df_movies[df_movies["genre"]=="Horror"].index

Int64Index([  80,  139,  439,  663,  858,  888, 1437, 2209, 2355, 2418, 2820,
            2874, 3032, 3180, 3324, 3415, 3524, 3592, 3633, 3689, 3712, 3836,
            3954, 3984, 4104, 4222, 4389, 4554, 4604, 4719, 4729, 4938, 4956,
            5066, 5081, 5163, 5203, 5215, 5288, 5324, 5538, 5673, 5911, 5944,
            5966, 6376, 6395, 6412, 6512, 6572, 6662, 6683, 6796, 6804, 6814,
            6887, 6898, 6958, 7086, 7350, 7478, 7514, 7805, 7851],
           dtype='int64')

**Formulas**

In [ ]:
df_movies.drop_duplicates('title')
df_movies.dropna('titles')
df_movies.fillna('vacio')
df_movies.isnull()*1
df_movies.head(2)
df_movies.info() #informacion de la matriz
df_movies.describe() #descripcion estadistica
df_movies.tail(4)
df_movies.memory_usage(deep=True) #la cantidad de memoria que usa cada tabla
df_movies['genre'].value_counts() #devuelve la lista de valores qye se encuentran en la columna
df_movies.sort_values('year')

In [6]:
#df_movies['base_year'] = int(df_movies['year'].apply(lambda x:x[1:5]))
df_movies['year'].apply(lambda x:x[1:5])

TypeError: 'float' object is not subscriptable